package de.walahi.novosmp.clan;

import de.walahi.novosmp.NovoSMPPlugin;
import de.walahi.novosmp.professions.BoosterCategory;
import de.walahi.novosmp.professions.ProfessionManager;
import de.walahi.smpcore.StatType;
import de.walahi.smpcore.api.event.ActionContext;
import de.walahi.smpcore.api.event.ActionSource;
import de.walahi.smpcore.api.event.EconomyTransactionEvent;
import de.walahi.smpcore.stats.StatsAccess;
import de.walahi.smpcore.gui.MenuFormat;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import net.kyori.adventure.text.format.TextColor;
import net.kyori.adventure.text.minimessage.MiniMessage;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.event.inventory.InventoryDragEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.inventory.ItemStack;

import java.sql.SQLException;
import java.util.*;
import org.bukkit.NamespacedKey;
import org.bukkit.persistence.PersistentDataType;
import java.util.logging.Level;

/** In-memory authorization/index facade backed by synchronous transactional mutations. */
public final class ClanManager implements Listener {
    record Invite(UUID clan,UUID sender,long until){}
    public record Progress(long prestige,long playtimeSeconds,long cost,long requiredPrestige,long requiredPlaytimeSeconds,boolean ready){}
    private final NovoSMPPlugin plugin; private final ClanConfig config; private final ClanRepository repo;
    private final StatsAccess stats; private final ProfessionManager professions;
    private final Map<UUID,Clan> clans=new LinkedHashMap<>(), byPlayer=new HashMap<>();
    private final Map<UUID,Invite> invites=new HashMap<>(); private final Map<UUID,Inventory> chests=new HashMap<>();
    private final Set<UUID> readyNoticeSent = new HashSet<>();
    private final MiniMessage mm=MiniMessage.miniMessage(); private final ClanPartyManager parties; private final ClanMenu menu;
    public ClanManager(NovoSMPPlugin plugin,StatsAccess stats,ProfessionManager professions){this.plugin=plugin;this.stats=stats;this.professions=professions;config=new ClanConfig(plugin);repo=new ClanRepository(plugin.storageManager());parties=new ClanPartyManager(this,config,professions.boosters());menu=new ClanMenu(plugin,this,config);try{clans.putAll(repo.loadAll());reindex();}catch(SQLException e){plugin.getLogger().log(Level.SEVERE,"Clans konnten nicht geladen werden",e);}}
    public void start(){plugin.getRankManager().tabSuffixProvider(this::tabSuffix);Bukkit.getPluginManager().registerEvents(this,plugin);} public boolean enabled(){return config.enabled();}
    public Clan clan(UUID player){return byPlayer.get(player);} public Collection<Clan> clans(){return List.copyOf(clans.values());}
    NovoSMPPlugin plugin(){ return plugin; }

    public boolean shouldClanGlow(Player viewer, Player target) {
        if (viewer == null || target == null) return false;
        Clan first = clan(viewer.getUniqueId()), second = clan(target.getUniqueId());
        if (first == null || second == null || !first.id().equals(second.id())) return false;
        return viewer.getPersistentDataContainer().has(glowKey(target.getUniqueId()), PersistentDataType.BYTE);
    }

    public boolean clanGlow(Player viewer, UUID target) {
        return viewer.getPersistentDataContainer().has(glowKey(target), PersistentDataType.BYTE);
    }

    public boolean toggleClanGlow(Player viewer, UUID target) {
        if (viewer.getUniqueId().equals(target) || clan(viewer.getUniqueId()) == null
                || clan(target) != clan(viewer.getUniqueId())) return false;
        NamespacedKey key = glowKey(target);
        boolean enabled = !viewer.getPersistentDataContainer().has(key, PersistentDataType.BYTE);
        if (enabled) viewer.getPersistentDataContainer().set(key, PersistentDataType.BYTE, (byte) 1);
        else viewer.getPersistentDataContainer().remove(key);
        if (plugin.friendManager() != null) plugin.friendManager().refreshGlow();
        return enabled;
    }

    private NamespacedKey glowKey(UUID target) { return new NamespacedKey(plugin, "clan_glow_" + target.toString().replace("-", "")); }
    public boolean sameClan(UUID a,UUID b){Clan x=clan(a),y=clan(b);return x!=null&&x==y;} public boolean friendlyFire(UUID a,UUID b){Clan c=clan(a);return c!=null&&c==clan(b)&&c.friendlyFire();}
    boolean canUpgrade(UUID player){Clan c=clan(player);Clan.Member m=member(c,player);return m!=null&&m.role().staff();}
    public void open(Player p){Clan c=clan(p.getUniqueId());if(c==null){replyRich(p,"<yellow>Du bist aktuell in keinem Clan.</yellow> <gray>Nutze <white>/clan help</white>.</gray>");return;}notifyIfReady(c);menu.main(p,c);}
    public void openList(Player p){menu.list(p);} public void openMembers(Player p){Clan c=clan(p.getUniqueId());if(c!=null)menu.members(p,c);} public void openHomes(Player p){Clan c=clan(p.getUniqueId());if(c!=null)menu.homes(p,c);} public void openSnitches(Player p){Clan c=clan(p.getUniqueId());if(c!=null)menu.snitches(p,c);}
    public void confirm(Player p,String title,String detail,Runnable action){menu.confirm(p,title,detail,action);}
    public void reply(Player player,String message){player.sendMessage(mm.deserialize("<dark_gray>[<gold>Clan</gold>]</dark_gray> ").append(Component.text(message,NamedTextColor.WHITE)));}
    public void replyRich(Player player,String message){player.sendMessage(mm.deserialize("<dark_gray>[<gold>Clan</gold>]</dark_gray> "+message));}
    public synchronized String create(Player p,String name,String tag){if(!enabled())return "Das Clan-System ist deaktiviert.";if(clan(p.getUniqueId())!=null)return "Du bist bereits in einem Clan.";boolean rankOk=config.createRank().equalsIgnoreCase("premium")?plugin.getRankManager().hasPremium(p):plugin.getRankManager().hasGroup(p,config.createRank());if(!rankOk)return "Du benötigst mindestens "+config.createRank()+".";if(!config.validName(name))return "Der Clanname muss "+config.nameMin()+"–"+config.nameMax()+" Zeichen lang sein.";if(!config.validTag(tag))return "Der Clan-Tag darf höchstens "+config.tagMax()+" Zeichen lang sein.";ClanRepository.Result r=repo.create(p.getUniqueId(),p.getName(),name,tag,config.createCost());if(r.status()==ClanRepository.Status.INSUFFICIENT)return "Du benötigst "+MenuFormat.integer(config.createCost())+" Coins für die Clan-Erstellung.";if(r.status()==ClanRepository.Status.EXISTS)return "Clanname oder Tag ist bereits vergeben.";if(r.status()!=ClanRepository.Status.SUCCESS)return "Clan konnte nicht gespeichert werden.";clans.put(r.clan().id(),r.clan());byPlayer.put(p.getUniqueId(),r.clan());if(plugin.getRankManager().hasPremiumPlus(p)){repo.simpleClanUpdate(r.clan(),"bonus_home",1);r.clan().bonusHome(true);}publish(p.getUniqueId(),EconomyTransactionEvent.Type.WITHDRAW,config.createCost(),r.before(),r.after(),"CLAN_CREATE");refreshTabs();return "Clan "+name+" ["+tag+"] wurde für "+MenuFormat.integer(config.createCost())+" Coins erstellt.";}
    public synchronized String invite(Player actor,Player target){Clan c=clan(actor.getUniqueId());Clan.Member m=member(c,actor.getUniqueId());if(c==null||m==null||!m.role().staff())return "Dafür fehlen dir Clan-Rechte.";if(clan(target.getUniqueId())!=null)return "Der Spieler ist bereits in einem Clan.";if(c.members().size()>=config.memberLimit(c.level()))return "Das Mitgliederlimit ist erreicht.";invites.put(target.getUniqueId(),new Invite(c.id(),actor.getUniqueId(),System.currentTimeMillis()+config.inviteMillis()));replyRich(target,"<yellow>"+c.name()+"</yellow> <gray>lädt dich ein.</gray> <green><click:run_command:'/clan accept'>[Annehmen]</click></green> <red><click:run_command:'/clan deny'>[Ablehnen]</click></red>");return "Einladung an "+target.getName()+" gesendet.";}
    public synchronized String accept(Player p){Invite i=invites.remove(p.getUniqueId());if(i==null||i.until()<System.currentTimeMillis())return "Keine gültige Einladung vorhanden.";Clan c=clans.get(i.clan());if(c==null||clan(p.getUniqueId())!=null||c.members().size()>=config.memberLimit(c.level()))return "Einladung kann nicht mehr angenommen werden.";if(repo.addMember(c,p.getUniqueId(),p.getName())!=ClanRepository.Status.SUCCESS)return "Beitritt konnte nicht gespeichert werden.";Clan.Member m=new Clan.Member(p.getUniqueId(),p.getName(),ClanRole.MEMBER,System.currentTimeMillis());c.members().put(m.id(),m);byPlayer.put(m.id(),c);broadcastSystem(c,"<green>✔</green> <yellow>"+p.getName()+"</yellow> <gray>ist dem Clan beigetreten.</gray>");refreshTabs();return "Du bist "+c.name()+" beigetreten.";}
    public String deny(UUID p){return invites.remove(p)!=null?"Einladung abgelehnt.":"Keine Einladung vorhanden.";}
    public synchronized String leave(Player p){Clan c=clan(p.getUniqueId());Clan.Member m=member(c,p.getUniqueId());if(c==null)return "Du bist in keinem Clan.";if(m.role()==ClanRole.LEADER&&c.members().size()>1)return "Übertrage zuerst die Leadership oder löse den Clan auf.";if(m.role()==ClanRole.LEADER)return "Nutze /clan disband.";return remove(c,m,p.getName()+" hat den Clan verlassen.");}
    public synchronized String kick(Player actor,String name){Clan c=clan(actor.getUniqueId());Clan.Member self=member(c,actor.getUniqueId()),target=find(c,name);if(self==null||!self.role().staff())return "Dafür fehlen dir Clan-Rechte.";if(target==null||target.role()==ClanRole.LEADER)return "Mitglied nicht gefunden.";if(self.role()==ClanRole.OFFICER&&target.role()!=ClanRole.MEMBER)return "Officer dürfen nur Member kicken.";return remove(c,target,target.name()+" wurde aus dem Clan entfernt.");}
    private String remove(Clan c,Clan.Member m,String msg){closeChest(m.id());parties.removePlayer(m.id());if(repo.removeMember(c,m)!=ClanRepository.Status.SUCCESS)return "Änderung konnte nicht gespeichert werden.";c.members().remove(m.id());byPlayer.remove(m.id());broadcastSystem(c,"<yellow>"+msg+"</yellow>");refreshTabs();return msg;}
    public synchronized String promoteDemote(Player actor,String name,boolean promote){Clan c=clan(actor.getUniqueId());Clan.Member self=member(c,actor.getUniqueId()),t=find(c,name);if(self==null||self.role()!=ClanRole.LEADER)return "Nur der Leader darf Rollen ändern.";if(t==null||t.role()==ClanRole.LEADER)return "Mitglied nicht gefunden.";ClanRole role=promote?ClanRole.OFFICER:ClanRole.MEMBER;if(promote&&t.role()!=ClanRole.MEMBER)return "Spieler ist bereits Officer.";if(promote&&c.members().values().stream().filter(x->x.role()==ClanRole.OFFICER).count()>=config.officers(c.level()))return "Das Officer-Limit ist erreicht.";if(repo.setRole(c,t.id(),role)!=ClanRepository.Status.SUCCESS)return "Rolle konnte nicht gespeichert werden.";c.members().put(t.id(),new Clan.Member(t.id(),t.name(),role,t.joinedAt()));return "Rolle aktualisiert.";}
    public synchronized String transfer(Player actor,String name){Clan c=clan(actor.getUniqueId());Clan.Member self=member(c,actor.getUniqueId()),t=find(c,name);if(self==null||self.role()!=ClanRole.LEADER)return "Nur der Leader darf übertragen.";if(t==null||t.id().equals(actor.getUniqueId()))return "Ziel ist kein anderes Clanmitglied.";if(!plugin.getRankManager().hasPremium(t.id()))return "Das Ziel benötigt mindestens Premium.";long officers=c.members().values().stream().filter(x->x.role()==ClanRole.OFFICER).count()-(t.role()==ClanRole.OFFICER?1:0);ClanRole old=officers<config.officers(c.level())?ClanRole.OFFICER:ClanRole.MEMBER;if(repo.transfer(c,self.id(),t.id(),old)!=ClanRepository.Status.SUCCESS)return "Transfer konnte nicht gespeichert werden.";c.members().put(self.id(),new Clan.Member(self.id(),self.name(),old,self.joinedAt()));c.members().put(t.id(),new Clan.Member(t.id(),t.name(),ClanRole.LEADER,t.joinedAt()));c.leader(t.id());if(plugin.getRankManager().hasPremiumPlus(t.id())&&!c.bonusHome()){repo.simpleClanUpdate(c,"bonus_home",1);c.bonusHome(true);}return "Leadership übertragen.";}
    public synchronized String deposit(Player p,long amount){Clan c=clan(p.getUniqueId());if(c==null)return "Du bist in keinem Clan.";if(amount<=0)return "Ungültiger Betrag.";ClanRepository.Result r=repo.deposit(c,p.getUniqueId(),amount);if(r.status()==ClanRepository.Status.INSUFFICIENT)return "Du besitzt nicht genügend Coins.";if(r.status()!=ClanRepository.Status.SUCCESS)return "Einzahlung fehlgeschlagen.";publish(p.getUniqueId(),EconomyTransactionEvent.Type.WITHDRAW,amount,r.before(),r.after(),"CLAN_DEPOSIT");notifyIfReady(c);return "✔ "+MenuFormat.integer(amount)+" Coins eingezahlt. Clan-Kasse: "+MenuFormat.integer(c.bank())+" Coins.";}
    public Progress progress(Clan c){if(c.level()>=10)return new Progress(0,0,0,0,0,false);try{int n=c.level()+1;long p=repo.prestige(c),t=repo.playtime(c),cost=config.upgradeCost(n),rp=config.prestige(n),rt=config.playtimeHours(n)*3600;return new Progress(p,t,cost,rp,rt,c.bank()>=cost&&p>=rp&&t>=rt);}catch(SQLException e){return new Progress(0,0,Long.MAX_VALUE,Long.MAX_VALUE,Long.MAX_VALUE,false);}}
    public synchronized String upgrade(Player p){Clan c=clan(p.getUniqueId());Clan.Member m=member(c,p.getUniqueId());if(m==null||!m.role().staff())return "Nur Leader und Officer dürfen upgraden.";if(c.level()>=10)return "Der Clan ist bereits Level 10.";Progress x=progress(c);if(!x.ready())return "Die Voraussetzungen sind noch nicht erfüllt.";Inventory open=chests.get(c.id());if(open!=null){saveChest(c.id());new ArrayList<>(open.getViewers()).forEach(v->v.closeInventory());chests.remove(c.id());}int old=c.level();ClanRepository.Status s=repo.upgrade(c,old,x.cost());if(s!=ClanRepository.Status.SUCCESS)return "Upgrade wurde bereits ausgeführt oder konnte nicht gespeichert werden.";readyNoticeSent.remove(c.id());broadcastSystem(c,"<gold><bold>⬆ Clan-Level "+c.level()+" erreicht!</bold></gold>");if(c.level()==10&&config.globalLevelTen())Bukkit.broadcast(mm.deserialize("<gold><bold>"+c.name()+" hat Clan-Level 10 erreicht!</bold></gold>"));return "Clan-Level "+c.level()+" erreicht.";}
    public synchronized String rename(Player p,String value,boolean tag){Clan c=clan(p.getUniqueId());Clan.Member m=member(c,p.getUniqueId());if(m==null||m.role()!=ClanRole.LEADER)return "Nur der Leader darf das ändern.";if(tag?!config.validTag(value):!config.validName(value))return "Name/Tag ist ungültig.";long now=System.currentTimeMillis(),last=tag?c.taggedAt():c.renamedAt(),cool=tag?config.tagCooldown():config.renameCooldown();if(now-last<cool)return "Cooldown verbleibend: "+((cool-(now-last)+3599999)/3600000)+" Stunden.";long cost=tag?config.tagCost():config.renameCost();ClanRepository.Status s=repo.updateIdentity(c,tag?"tag":"name",value,cost,now);if(s==ClanRepository.Status.SUCCESS){if(tag)refreshTabs();return "Änderung für "+MenuFormat.integer(cost)+" Coins gespeichert.";}return s==ClanRepository.Status.INSUFFICIENT?"Clan-Kasse reicht nicht aus.":s==ClanRepository.Status.EXISTS?"Bereits vergeben.":"Änderung fehlgeschlagen.";}
    public synchronized String tagColor(Player p,String color){Clan c=clan(p.getUniqueId());Clan.Member m=member(c,p.getUniqueId());if(m==null||m.role()!=ClanRole.LEADER)return "Nur der Leader darf die Tag-Farbe ändern.";if(!plugin.getRankManager().hasPremiumPlus(p))return "Dafür benötigt der aktuelle Leader PremiumPlus.";if(color==null||!color.matches("#[0-9A-Fa-f]{6}"))return "Nutze einen gültigen Hex-Code wie #A855F7.";if(repo.simpleClanUpdate(c,"tag_color",color)!=ClanRepository.Status.SUCCESS)return "Änderung fehlgeschlagen.";c.tagColor(color.toUpperCase(Locale.ROOT));refreshTabs();return "Tag-Farbe geändert.";}
    public synchronized String friendlyFire(Player p,boolean on){Clan c=clan(p.getUniqueId());Clan.Member m=member(c,p.getUniqueId());if(m==null||!m.role().staff())return "Dafür fehlen dir Clan-Rechte.";if(c.level()<config.ffUnlock())return "Friendly Fire ist noch nicht freigeschaltet.";if(repo.simpleClanUpdate(c,"friendly_fire",on?1:0)!=ClanRepository.Status.SUCCESS)return "Änderung fehlgeschlagen.";c.friendlyFire(on);return "Friendly Fire ist jetzt "+(on?"AN":"AUS")+".";}
    public List<ClanRepository.Home> homes(Clan c){try{return repo.homes(c.id());}catch(SQLException e){return List.of();}}
    public synchronized String setHome(Player p,String name){Clan c=clan(p.getUniqueId());Clan.Member m=member(c,p.getUniqueId());if(m==null||!m.role().staff())return "Dafür fehlen dir Clan-Rechte.";String n=name.toLowerCase(Locale.ROOT);if(n.length()>config.homeNameMax()||!n.matches("[a-z0-9_-]+"))return "Ungültiger Home-Name.";List<ClanRepository.Home> homes=homes(c);boolean exists=homes.stream().anyMatch(h->h.name().equals(n));if(!exists&&homes.size()>=config.homes(c.level(),c.bonusHome()))return "Kein Clan-Home-Slot frei.";return repo.setHome(c.id(),n,name,p.getLocation())==ClanRepository.Status.SUCCESS?"Clan-Home gespeichert.":"Speichern fehlgeschlagen.";}
    public String deleteHome(Player p,String name){Clan c=clan(p.getUniqueId());Clan.Member m=member(c,p.getUniqueId());if(m==null||!m.role().staff())return "Dafür fehlen dir Clan-Rechte.";return repo.deleteHome(c.id(),name.toLowerCase(Locale.ROOT))==ClanRepository.Status.SUCCESS?"Clan-Home gelöscht.":"Clan-Home nicht gefunden.";}
    public String teleportHome(Player p,String name){Clan c=clan(p.getUniqueId());if(c==null)return "Du bist in keinem Clan.";if(plugin.combatManager()!=null&&plugin.combatManager().isInCombat(p.getUniqueId()))return "Während Combat kannst du kein Clan-Home nutzen.";ClanRepository.Home h=homes(c).stream().filter(x->x.name().equalsIgnoreCase(name)).findFirst().orElse(null);if(h==null)return "Clan-Home nicht gefunden.";plugin.teleportClanHome(p,h.location(),h.display());return "Teleport gestartet.";}
    public synchronized void openChest(Player p){Clan c=clan(p.getUniqueId());if(c==null)return;int size=config.chestRows(c.level())*9;Inventory inv=chests.get(c.id());if(inv==null||inv.getSize()!=size){Inventory next=Bukkit.createInventory(new ChestHolder(c.id()),size,mm.deserialize("<dark_gray>Clan-EC • "+c.name()+"</dark_gray>"));try{next.setContents(repo.loadChest(c.id(),size));}catch(Exception e){plugin.getLogger().log(Level.SEVERE,"Clan-EC konnte nicht geladen werden",e);return;}if(inv!=null)next.setContents(Arrays.copyOf(inv.getContents(),size));chests.put(c.id(),next);inv=next;}p.openInventory(inv);}
    public UUID chestClan(Inventory inventory){return inventory!=null&&inventory.getHolder() instanceof ChestHolder h?h.clan:null;}
    public String clanName(UUID clanId){Clan c=clans.get(clanId);return c==null?null:c.name();}
    private void saveChest(UUID clan){Inventory i=chests.get(clan);if(i==null)return;try{repo.saveChest(clan,i.getContents());}catch(Exception e){plugin.getLogger().log(Level.SEVERE,"Clan-EC konnte nicht gespeichert werden",e);}}
    public synchronized String snitch(Player p,String name,boolean remove){Clan c=clan(p.getUniqueId());Clan.Member m=member(c,p.getUniqueId());if(m==null||!m.role().staff())return "Dafür fehlen dir Clan-Rechte.";ClanRepository.Snitch existing;try{existing=repo.snitches(c.id()).stream().filter(x->x.name().equalsIgnoreCase(name)).findFirst().orElse(null);if(remove){if(existing==null)return "Snitch nicht gefunden.";return repo.unsnitch(c.id(),existing.id())==ClanRepository.Status.SUCCESS?"Snitch entfernt.":"Änderung fehlgeschlagen.";}if(find(c,name)!=null)return "Aktuelle Mitglieder können nicht markiert werden.";UUID id=existing==null?formerId(c,name):existing.id();if(id==null||!repo.former(c.id(),id))return "Nur ehemalige Mitglieder dieses Clans sind zulässig.";return repo.snitch(c.id(),id,name,p.getUniqueId(),p.getName())==ClanRepository.Status.SUCCESS?"Snitch markiert.":"Änderung fehlgeschlagen.";}catch(SQLException e){return "Datenbankfehler.";}}
    public List<ClanRepository.Snitch> snitches(Clan c){try{return repo.snitches(c.id());}catch(SQLException e){return List.of();}}
    private UUID formerId(Clan c,String name){try{return repo.snitches(c.id()).stream().filter(x->x.name().equalsIgnoreCase(name)).map(ClanRepository.Snitch::id).findFirst().orElseGet(()->Bukkit.getOfflinePlayer(name).getUniqueId());}catch(Exception e){return null;}}
    public synchronized String disband(Player p){Clan c=clan(p.getUniqueId());Clan.Member m=member(c,p.getUniqueId());if(m==null||m.role()!=ClanRole.LEADER)return "Nur der Leader darf auflösen.";Inventory i=chests.get(c.id());if(i!=null&&Arrays.stream(i.getContents()).anyMatch(x->x!=null&&!x.getType().isAir()))return "Leere zuerst die Clan-EC vollständig.";try{if(Arrays.stream(repo.loadChest(c.id(),config.chestRows(c.level())*9)).anyMatch(Objects::nonNull))return "Leere zuerst die Clan-EC vollständig.";}catch(Exception e){return "Clan-EC konnte nicht geprüft werden.";}if(i!=null)i.getViewers().forEach(v->v.closeInventory());parties.disbandClan(c.id());if(repo.disband(c)!=ClanRepository.Status.SUCCESS)return "Auflösung fehlgeschlagen.";clans.remove(c.id());c.members().keySet().forEach(byPlayer::remove);chests.remove(c.id());refreshTabs();return "Clan aufgelöst; die Clan-Kasse wurde nicht erstattet.";}
    public ClanPartyManager parties(){return parties;} public double professionMultiplier(UUID player){return 1D+parties.professionBonus(player);} public double sharedLumiTier(UUID player){return parties.sharedLumiTier(player);} public int lumiInterval(double tier){return config.lumiInterval(tier);} public int lumiRewardMin(){return config.lumiMin();} public int lumiRewardMax(){return config.lumiMax();}
    @EventHandler public void quit(PlayerQuitEvent e){parties.removePlayer(e.getPlayer().getUniqueId());invites.remove(e.getPlayer().getUniqueId());}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true) public void chestClick(InventoryClickEvent e){if(e.getView().getTopInventory().getHolder() instanceof ChestHolder h){if(clan(e.getWhoClicked().getUniqueId())==null||!clan(e.getWhoClicked().getUniqueId()).id().equals(h.clan)){e.setCancelled(true);e.getWhoClicked().closeInventory();return;}Bukkit.getScheduler().runTask(plugin,()->saveChest(h.clan));}}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true) public void chestDrag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof ChestHolder h)Bukkit.getScheduler().runTask(plugin,()->saveChest(h.clan));}
    @EventHandler public void chestClose(InventoryCloseEvent e){if(e.getInventory().getHolder() instanceof ChestHolder h)saveChest(h.clan);}
    public void shutdown(){for(UUID id:new ArrayList<>(chests.keySet()))saveChest(id);chests.clear();plugin.getRankManager().tabSuffixProvider(null);}
    private Component tabSuffix(Player player){Clan c=clan(player.getUniqueId());if(c==null)return Component.empty();TextColor color=TextColor.fromHexString(c.tagColor());if(color==null)color=NamedTextColor.GRAY;return Component.text(" [",NamedTextColor.GRAY).append(Component.text(c.tag(),color)).append(Component.text("]",NamedTextColor.GRAY));}
    private void refreshTabs(){plugin.getRankManager().applyAll();}
    private void closeChest(UUID player){Player p=Bukkit.getPlayer(player);if(p!=null)p.closeInventory();}
    private void reindex(){byPlayer.clear();for(Clan c:clans.values())for(UUID id:c.members().keySet())byPlayer.put(id,c);}
    private Clan.Member member(Clan c,UUID id){return c==null?null:c.members().get(id);} private Clan.Member find(Clan c,String name){return c==null?null:c.members().values().stream().filter(m->m.name().equalsIgnoreCase(name)).findFirst().orElse(null);}
    private void broadcast(Clan c,String raw){for(UUID id:c.members().keySet()){Player p=Bukkit.getPlayer(id);if(p!=null)p.sendMessage(mm.deserialize(raw));}}
    private void broadcastSystem(Clan c,String raw){broadcast(c,"<dark_gray>[<gold>Clan</gold>]</dark_gray> "+raw);}
    private void notifyIfReady(Clan c){Progress progress=progress(c);if(!progress.ready()||!readyNoticeSent.add(c.id()))return;for(Clan.Member member:c.members().values()){if(!member.role().staff())continue;Player online=Bukkit.getPlayer(member.id());if(online!=null){reply(online,"✔ Clan-Level "+(c.level()+1)+" ist verfügbar.");online.sendRichMessage("<gray>Öffne <yellow>/clan</yellow> zum Aufsteigen.</gray>");}}}
    public void clanChat(Player sender,String message){Clan c=clan(sender.getUniqueId());if(c==null){replyRich(sender,"<red>Du bist in keinem Clan.</red>");return;}Clan.Member m=c.members().get(sender.getUniqueId());broadcast(c,"<dark_gray>[</dark_gray><"+c.tagColor()+">"+c.tag()+"</"+c.tagColor()+"><dark_gray>]</dark_gray> <gray>["+m.role().name()+"]</gray> <yellow>"+sender.getName()+":</yellow> <white>"+escape(message)+"</white>");}
    private String escape(String s){return s.replace("<","\\<").replace(">","\\>");}
    private void publish(UUID p,EconomyTransactionEvent.Type t,long a,long b,long after,String reason){Bukkit.getPluginManager().callEvent(new EconomyTransactionEvent(p,t,a,b,after,reason,ActionContext.player(ActionSource.COMMAND,p)));}
    private static final class ChestHolder implements InventoryHolder{final UUID clan;ChestHolder(UUID c){clan=c;}public Inventory getInventory(){return null;}}
}
