package de.walahi.novosmp.quests;

public enum QuestType {
    MOB_KILL, ENTITY_KILL, BOSS_KILL, TAME, BREED, EGG_THROW, FISH_CATCH,
    ORE_BREAK, MATERIAL_BREAK, BLOCK_BREAK, ELYTRA_DISTANCE, BOAT_DISTANCE, ENCHANT
}
